# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    companieshouse: 'companieshouse.csv'
    comp_officies: 'companieshouse_officies.csv'
    comp_filing: 'companieshouse_filing.csv'
    apikeys: '%env(resolve:APIKEYS)%'
    
    accounts:
        acc_0:
            apikey: KAtZ_yE25A6xbqmeZ6Y0H-gg6fMHXilZggTYjN_W
            proxy: 138.59.206.94:9821:wKHjyt:aboKCe
        acc_1:
            apikey: whoplcFCp1fiZH2gdJbeKEeIICb-2XoMVrMaef-2
            proxy: 138.59.206.83:9561:wKHjyt:aboKCe
        acc_2:
            apikey: 7-D6maM6uwv7Pd7Z55zhzr7RwfiUKWuvcPma9NzP
            proxy: 138.59.206.71:9978:wKHjyt:aboKCe        
        acc_3:
            apikey: QYKt0E6SlCBfycfBtpzadKFe3f_UWmQPG2DrWea9
            proxy: 138.59.206.53:9635:wKHjyt:aboKCe   
        acc_4:
            apikey: YpGcljqCvkCveMrvVD7qcBbjOs7w9i1pobfk-FAq
            proxy: 138.59.206.43:9294:wKHjyt:aboKCe
        acc_5:
            apikey: Q7FK2x5sgcyE903J-jjQCx2aWLdVnaFCIbAzHiyF
            proxy: 138.59.206.33:9589:wKHjyt:aboKCe    
        acc_6:
            apikey: 5l23qrREEAd4nDhlXt8137JEXVfOrl8-EUDXolqj
            proxy: 138.59.206.26:9475:wKHjyt:aboKCe
        acc_7:
            apikey: qWdhSa71c-GKedkPpJ5hpUEMPqjj1akensftL4cP
            proxy: 138.59.206.9:9749:wKHjyt:aboKCe
        acc_8:
            apikey: c9lCRNe3UZuzUPanIQnO47Oz7fLfZ7rS4UuEwSEd
            proxy: 138.59.205.234:9216:wKHjyt:aboKCe    
        acc_9:
            apikey: RkxpupMNez46BLUwttXDfIL5rw7d5kg3JYxyHZNN
            proxy: 138.59.205.208:9702:wKHjyt:aboKCe           

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
